# Generated by Django 5.2.9 on 2025-12-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_homogeneo', models.CharField(max_length=255)),
                ('producto_recomendado', models.CharField(max_length=255)),
                ('pvp_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puc_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margen_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('penetracion_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('a_sustituir', models.TextField()),
                ('ahorro_potencial', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
