# Generated by Django 5.2.9 on 2025-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_homogeneo', models.CharField(max_length=255, unique=True)),
                ('laboratorio_preferente', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
