# Generated by Django 5.2.9 on 2025-12-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_preferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='farmacia_id',
            field=models.CharField(default='HF280050001', max_length=50),
        ),
    ]
