# Generated by Django 5.2.9 on 2025-12-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilfarmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='codigo_nacional',
            field=models.CharField(blank=True, help_text='CN del producto recomendado', max_length=20, null=True),
        ),
    ]
