# Generated by Django 5.2.9 on 2025-12-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_oportunidad_codigo_nacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidad',
            options={'ordering': ['-ahorro_potencial']},
        ),
        migrations.AddField(
            model_name='preferencia',
            name='farmacia_id',
            field=models.CharField(default='HF280050001', max_length=50),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='grupo_homogeneo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='preferencia',
            unique_together={('grupo_homogeneo', 'farmacia_id')},
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['farmacia_id', 'ahorro_potencial'], name='core_oportu_farmaci_6367ac_idx'),
        ),
        migrations.AddIndex(
            model_name='preferencia',
            index=models.Index(fields=['farmacia_id', 'activo'], name='core_prefer_farmaci_96edee_idx'),
        ),
    ]
