# Generated by Django 5.2.9 on 2025-12-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OportunidadEFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia_id', models.CharField(db_index=True, max_length=50)),
                ('id_agrupacion', models.IntegerField()),
                ('categoria_nombre', models.CharField(max_length=200)),
                ('producto_recomendado', models.CharField(max_length=255)),
                ('pvp_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puc_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margen_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('penetracion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('a_sustituir', models.TextField(blank=True)),
                ('ahorro_potencial', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('farmacia_id', 'id_agrupacion')},
            },
        ),
    ]
