# Generated by Django 5.2.9 on 2025-12-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunidadefp',
            options={'ordering': ['-ahorro_potencial']},
        ),
        migrations.RemoveField(
            model_name='oportunidadefp',
            name='categoria_nombre',
        ),
        migrations.RemoveField(
            model_name='oportunidadefp',
            name='penetracion_pct',
        ),
        migrations.RemoveField(
            model_name='oportunidadefp',
            name='puc_medio',
        ),
        migrations.AddField(
            model_name='oportunidadefp',
            name='familia',
            field=models.CharField(default='Otras', max_length=100),
        ),
        migrations.AddField(
            model_name='oportunidadefp',
            name='nombre_grupo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidadefp',
            name='subfamilia',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='oportunidadefp',
            name='pvp_medio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
