# Generated by Django 5.2.9 on 2025-12-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efp', '0002_alter_oportunidadefp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidadefp',
            name='codigo_nacional',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
