# Generated by Django 5.2.9 on 2025-12-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efp', '0003_oportunidadefp_codigo_nacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaEFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia_id', models.CharField(db_index=True, max_length=50)),
                ('id_agrupacion', models.IntegerField()),
                ('producto_preferido', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('farmacia_id', 'id_agrupacion')},
            },
        ),
    ]
