# Generated by Django 5.2.9 on 2025-12-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efp', '0004_preferenciaefp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oportunidadefp',
            index=models.Index(fields=['farmacia_id', 'familia'], name='efp_oportun_farmaci_8d5429_idx'),
        ),
    ]
